# Jekyll technical configuration!
#

## previous version: 
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
github: metadata

##
minimal_mistakes_skin    : "aqua" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "de"
title                    : "ESA"
title_separator          : "-"
name                     : ""
description              : "Effektive Softwarearchitekturen"
url                      : "https://esabuch.de" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : ""  # the subpath of your site, e.g. "/blog"
repository               : "gernotstarke/esabuch.de-site" # GitHub username/repo-name
teaser                   : /images/site-header.png # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
permalink                : none

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
# Social Sharing
twitter:
  username               : gernotstarke
  # For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             : "Dr. Gernot Starke"
  avatar           : /images/Gernot-avatar-2016.jpg # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : ""
  location         : "Köln"
  email            : gs@gernotstarke.de
  uri              : https://gernotstarke.de
  github           : gernotstarke
  google_plus      :
  stack_overflow   :
  twitter          : gernotstarke
  xing             : 

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - Dockerfile
  - _docker-compose*
  - _develop-site.sh
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - config
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - README
  - tmp
  - zz-originale
  - zz-production-site

keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: coderay


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
collections:
  addons:
   output: true
   permalink: /:collection/:path.html

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
