# docker-compose definition for generating a release-version.
#
version: '2'

services:
  jekyll:
    build: .
    image: gernotstarke:esabuch-site
    command: jekyll build --destination zz-site --no-watch
    volumes:
      - .:/srv/jekyll
      - $PWD/_config.yml:/srv/jekyll/_config.yml
