# docker-compose definition for developing the site.
#
version: '2'

services:
  esabuch-jekyll:
    build: .
    image: esabuch-site
    command: jekyll serve --trace --host 0.0.0.0 --watch --config _config.yml,_config-dev.yml
    environment:
      - JEKYLL_ENV=development
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
#      - $PWD/_config-dev.yml:/srv/jekyll/_config.yml
