# docker-compose definition for generating a release-version
# (that has to be ftp'd or rcp'd to the production webserver)
#
version: '2'

services:
  esabuch-jekyll:
    build: .
    image: esabuch-site
    command: jekyll build --destination zz-production-site --no-watch
    volumes:
      - .:/srv/jekyll
      - $PWD/_config.yml:/srv/jekyll/_config.yml
